// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.2
// source: proto/agent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AgentService_Authenticate_FullMethodName     = "/serverhub.AgentService/Authenticate"
	AgentService_GetSystemInfo_FullMethodName    = "/serverhub.AgentService/GetSystemInfo"
	AgentService_GetMetrics_FullMethodName       = "/serverhub.AgentService/GetMetrics"
	AgentService_ExecuteCommand_FullMethodName   = "/serverhub.AgentService/ExecuteCommand"
	AgentService_ExecuteShell_FullMethodName     = "/serverhub.AgentService/ExecuteShell"
	AgentService_ReadFile_FullMethodName         = "/serverhub.AgentService/ReadFile"
	AgentService_WriteFile_FullMethodName        = "/serverhub.AgentService/WriteFile"
	AgentService_ListDirectory_FullMethodName    = "/serverhub.AgentService/ListDirectory"
	AgentService_DeleteFile_FullMethodName       = "/serverhub.AgentService/DeleteFile"
	AgentService_UploadFile_FullMethodName       = "/serverhub.AgentService/UploadFile"
	AgentService_DownloadFile_FullMethodName     = "/serverhub.AgentService/DownloadFile"
	AgentService_TailLog_FullMethodName          = "/serverhub.AgentService/TailLog"
	AgentService_ListServices_FullMethodName     = "/serverhub.AgentService/ListServices"
	AgentService_ServiceAction_FullMethodName    = "/serverhub.AgentService/ServiceAction"
	AgentService_ListProcesses_FullMethodName    = "/serverhub.AgentService/ListProcesses"
	AgentService_KillProcess_FullMethodName      = "/serverhub.AgentService/KillProcess"
	AgentService_SearchDockerHub_FullMethodName  = "/serverhub.AgentService/SearchDockerHub"
	AgentService_ProxyHttpRequest_FullMethodName = "/serverhub.AgentService/ProxyHttpRequest"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	// 认证
	Authenticate(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// 系统信息
	GetSystemInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SystemInfo, error)
	GetMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (AgentService_GetMetricsClient, error)
	// 命令执行
	ExecuteCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	ExecuteShell(ctx context.Context, opts ...grpc.CallOption) (AgentService_ExecuteShellClient, error)
	// 文件操作
	ReadFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileContent, error)
	WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	ListDirectory(ctx context.Context, in *DirRequest, opts ...grpc.CallOption) (*DirContent, error)
	DeleteFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	// 流式文件上传 - 支持大文件
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (AgentService_UploadFileClient, error)
	// 流式文件下载 - 支持大文件
	DownloadFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (AgentService_DownloadFileClient, error)
	// 日志流
	TailLog(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (AgentService_TailLogClient, error)
	// 服务管理
	ListServices(ctx context.Context, in *ServiceFilter, opts ...grpc.CallOption) (*ServiceList, error)
	ServiceAction(ctx context.Context, in *ServiceActionRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	// 进程管理
	ListProcesses(ctx context.Context, in *ProcessFilter, opts ...grpc.CallOption) (*ProcessList, error)
	KillProcess(ctx context.Context, in *KillProcessRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	// Docker Hub 搜索（通过服务端代理）
	SearchDockerHub(ctx context.Context, in *DockerSearchRequest, opts ...grpc.CallOption) (*DockerSearchResponse, error)
	// HTTP 代理请求（通用）
	ProxyHttpRequest(ctx context.Context, in *HttpProxyRequest, opts ...grpc.CallOption) (*HttpProxyResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Authenticate(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, AgentService_Authenticate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetSystemInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SystemInfo, error) {
	out := new(SystemInfo)
	err := c.cc.Invoke(ctx, AgentService_GetSystemInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (AgentService_GetMetricsClient, error) {
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_GetMetrics_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &agentServiceGetMetricsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AgentService_GetMetricsClient interface {
	Recv() (*Metrics, error)
	grpc.ClientStream
}

type agentServiceGetMetricsClient struct {
	grpc.ClientStream
}

func (x *agentServiceGetMetricsClient) Recv() (*Metrics, error) {
	m := new(Metrics)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *agentServiceClient) ExecuteCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, AgentService_ExecuteCommand_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ExecuteShell(ctx context.Context, opts ...grpc.CallOption) (AgentService_ExecuteShellClient, error) {
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[1], AgentService_ExecuteShell_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &agentServiceExecuteShellClient{stream}
	return x, nil
}

type AgentService_ExecuteShellClient interface {
	Send(*ShellInput) error
	Recv() (*ShellOutput, error)
	grpc.ClientStream
}

type agentServiceExecuteShellClient struct {
	grpc.ClientStream
}

func (x *agentServiceExecuteShellClient) Send(m *ShellInput) error {
	return x.ClientStream.SendMsg(m)
}

func (x *agentServiceExecuteShellClient) Recv() (*ShellOutput, error) {
	m := new(ShellOutput)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *agentServiceClient) ReadFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileContent, error) {
	out := new(FileContent)
	err := c.cc.Invoke(ctx, AgentService_ReadFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, AgentService_WriteFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListDirectory(ctx context.Context, in *DirRequest, opts ...grpc.CallOption) (*DirContent, error) {
	out := new(DirContent)
	err := c.cc.Invoke(ctx, AgentService_ListDirectory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DeleteFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, AgentService_DeleteFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (AgentService_UploadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[2], AgentService_UploadFile_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &agentServiceUploadFileClient{stream}
	return x, nil
}

type AgentService_UploadFileClient interface {
	Send(*FileChunk) error
	CloseAndRecv() (*UploadResponse, error)
	grpc.ClientStream
}

type agentServiceUploadFileClient struct {
	grpc.ClientStream
}

func (x *agentServiceUploadFileClient) Send(m *FileChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *agentServiceUploadFileClient) CloseAndRecv() (*UploadResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *agentServiceClient) DownloadFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (AgentService_DownloadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[3], AgentService_DownloadFile_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &agentServiceDownloadFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AgentService_DownloadFileClient interface {
	Recv() (*FileChunk, error)
	grpc.ClientStream
}

type agentServiceDownloadFileClient struct {
	grpc.ClientStream
}

func (x *agentServiceDownloadFileClient) Recv() (*FileChunk, error) {
	m := new(FileChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *agentServiceClient) TailLog(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (AgentService_TailLogClient, error) {
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[4], AgentService_TailLog_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &agentServiceTailLogClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AgentService_TailLogClient interface {
	Recv() (*LogLine, error)
	grpc.ClientStream
}

type agentServiceTailLogClient struct {
	grpc.ClientStream
}

func (x *agentServiceTailLogClient) Recv() (*LogLine, error) {
	m := new(LogLine)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *agentServiceClient) ListServices(ctx context.Context, in *ServiceFilter, opts ...grpc.CallOption) (*ServiceList, error) {
	out := new(ServiceList)
	err := c.cc.Invoke(ctx, AgentService_ListServices_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ServiceAction(ctx context.Context, in *ServiceActionRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, AgentService_ServiceAction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListProcesses(ctx context.Context, in *ProcessFilter, opts ...grpc.CallOption) (*ProcessList, error) {
	out := new(ProcessList)
	err := c.cc.Invoke(ctx, AgentService_ListProcesses_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) KillProcess(ctx context.Context, in *KillProcessRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, AgentService_KillProcess_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SearchDockerHub(ctx context.Context, in *DockerSearchRequest, opts ...grpc.CallOption) (*DockerSearchResponse, error) {
	out := new(DockerSearchResponse)
	err := c.cc.Invoke(ctx, AgentService_SearchDockerHub_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ProxyHttpRequest(ctx context.Context, in *HttpProxyRequest, opts ...grpc.CallOption) (*HttpProxyResponse, error) {
	out := new(HttpProxyResponse)
	err := c.cc.Invoke(ctx, AgentService_ProxyHttpRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility
type AgentServiceServer interface {
	// 认证
	Authenticate(context.Context, *AuthRequest) (*AuthResponse, error)
	// 系统信息
	GetSystemInfo(context.Context, *Empty) (*SystemInfo, error)
	GetMetrics(*MetricsRequest, AgentService_GetMetricsServer) error
	// 命令执行
	ExecuteCommand(context.Context, *CommandRequest) (*CommandResponse, error)
	ExecuteShell(AgentService_ExecuteShellServer) error
	// 文件操作
	ReadFile(context.Context, *FileRequest) (*FileContent, error)
	WriteFile(context.Context, *WriteFileRequest) (*ActionResponse, error)
	ListDirectory(context.Context, *DirRequest) (*DirContent, error)
	DeleteFile(context.Context, *FileRequest) (*ActionResponse, error)
	// 流式文件上传 - 支持大文件
	UploadFile(AgentService_UploadFileServer) error
	// 流式文件下载 - 支持大文件
	DownloadFile(*FileRequest, AgentService_DownloadFileServer) error
	// 日志流
	TailLog(*LogRequest, AgentService_TailLogServer) error
	// 服务管理
	ListServices(context.Context, *ServiceFilter) (*ServiceList, error)
	ServiceAction(context.Context, *ServiceActionRequest) (*ActionResponse, error)
	// 进程管理
	ListProcesses(context.Context, *ProcessFilter) (*ProcessList, error)
	KillProcess(context.Context, *KillProcessRequest) (*ActionResponse, error)
	// Docker Hub 搜索（通过服务端代理）
	SearchDockerHub(context.Context, *DockerSearchRequest) (*DockerSearchResponse, error)
	// HTTP 代理请求（通用）
	ProxyHttpRequest(context.Context, *HttpProxyRequest) (*HttpProxyResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAgentServiceServer struct {
}

func (UnimplementedAgentServiceServer) Authenticate(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedAgentServiceServer) GetSystemInfo(context.Context, *Empty) (*SystemInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSystemInfo not implemented")
}
func (UnimplementedAgentServiceServer) GetMetrics(*MetricsRequest, AgentService_GetMetricsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedAgentServiceServer) ExecuteCommand(context.Context, *CommandRequest) (*CommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedAgentServiceServer) ExecuteShell(AgentService_ExecuteShellServer) error {
	return status.Errorf(codes.Unimplemented, "method ExecuteShell not implemented")
}
func (UnimplementedAgentServiceServer) ReadFile(context.Context, *FileRequest) (*FileContent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedAgentServiceServer) WriteFile(context.Context, *WriteFileRequest) (*ActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedAgentServiceServer) ListDirectory(context.Context, *DirRequest) (*DirContent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDirectory not implemented")
}
func (UnimplementedAgentServiceServer) DeleteFile(context.Context, *FileRequest) (*ActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedAgentServiceServer) UploadFile(AgentService_UploadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedAgentServiceServer) DownloadFile(*FileRequest, AgentService_DownloadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedAgentServiceServer) TailLog(*LogRequest, AgentService_TailLogServer) error {
	return status.Errorf(codes.Unimplemented, "method TailLog not implemented")
}
func (UnimplementedAgentServiceServer) ListServices(context.Context, *ServiceFilter) (*ServiceList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedAgentServiceServer) ServiceAction(context.Context, *ServiceActionRequest) (*ActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServiceAction not implemented")
}
func (UnimplementedAgentServiceServer) ListProcesses(context.Context, *ProcessFilter) (*ProcessList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProcesses not implemented")
}
func (UnimplementedAgentServiceServer) KillProcess(context.Context, *KillProcessRequest) (*ActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KillProcess not implemented")
}
func (UnimplementedAgentServiceServer) SearchDockerHub(context.Context, *DockerSearchRequest) (*DockerSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchDockerHub not implemented")
}
func (UnimplementedAgentServiceServer) ProxyHttpRequest(context.Context, *HttpProxyRequest) (*HttpProxyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProxyHttpRequest not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Authenticate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Authenticate(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetSystemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetSystemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetSystemInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetSystemInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).GetMetrics(m, &agentServiceGetMetricsServer{stream})
}

type AgentService_GetMetricsServer interface {
	Send(*Metrics) error
	grpc.ServerStream
}

type agentServiceGetMetricsServer struct {
	grpc.ServerStream
}

func (x *agentServiceGetMetricsServer) Send(m *Metrics) error {
	return x.ServerStream.SendMsg(m)
}

func _AgentService_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ExecuteCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ExecuteCommand(ctx, req.(*CommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ExecuteShell_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).ExecuteShell(&agentServiceExecuteShellServer{stream})
}

type AgentService_ExecuteShellServer interface {
	Send(*ShellOutput) error
	Recv() (*ShellInput, error)
	grpc.ServerStream
}

type agentServiceExecuteShellServer struct {
	grpc.ServerStream
}

func (x *agentServiceExecuteShellServer) Send(m *ShellOutput) error {
	return x.ServerStream.SendMsg(m)
}

func (x *agentServiceExecuteShellServer) Recv() (*ShellInput, error) {
	m := new(ShellInput)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _AgentService_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReadFile(ctx, req.(*FileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_WriteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).WriteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_WriteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).WriteFile(ctx, req.(*WriteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListDirectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListDirectory(ctx, req.(*DirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DeleteFile(ctx, req.(*FileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).UploadFile(&agentServiceUploadFileServer{stream})
}

type AgentService_UploadFileServer interface {
	SendAndClose(*UploadResponse) error
	Recv() (*FileChunk, error)
	grpc.ServerStream
}

type agentServiceUploadFileServer struct {
	grpc.ServerStream
}

func (x *agentServiceUploadFileServer) SendAndClose(m *UploadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *agentServiceUploadFileServer) Recv() (*FileChunk, error) {
	m := new(FileChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _AgentService_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).DownloadFile(m, &agentServiceDownloadFileServer{stream})
}

type AgentService_DownloadFileServer interface {
	Send(*FileChunk) error
	grpc.ServerStream
}

type agentServiceDownloadFileServer struct {
	grpc.ServerStream
}

func (x *agentServiceDownloadFileServer) Send(m *FileChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _AgentService_TailLog_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).TailLog(m, &agentServiceTailLogServer{stream})
}

type AgentService_TailLogServer interface {
	Send(*LogLine) error
	grpc.ServerStream
}

type agentServiceTailLogServer struct {
	grpc.ServerStream
}

func (x *agentServiceTailLogServer) Send(m *LogLine) error {
	return x.ServerStream.SendMsg(m)
}

func _AgentService_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListServices(ctx, req.(*ServiceFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ServiceAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ServiceAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ServiceAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ServiceAction(ctx, req.(*ServiceActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListProcesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListProcesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListProcesses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListProcesses(ctx, req.(*ProcessFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_KillProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).KillProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_KillProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).KillProcess(ctx, req.(*KillProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SearchDockerHub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DockerSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SearchDockerHub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_SearchDockerHub_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SearchDockerHub(ctx, req.(*DockerSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ProxyHttpRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HttpProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ProxyHttpRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ProxyHttpRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ProxyHttpRequest(ctx, req.(*HttpProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "serverhub.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _AgentService_Authenticate_Handler,
		},
		{
			MethodName: "GetSystemInfo",
			Handler:    _AgentService_GetSystemInfo_Handler,
		},
		{
			MethodName: "ExecuteCommand",
			Handler:    _AgentService_ExecuteCommand_Handler,
		},
		{
			MethodName: "ReadFile",
			Handler:    _AgentService_ReadFile_Handler,
		},
		{
			MethodName: "WriteFile",
			Handler:    _AgentService_WriteFile_Handler,
		},
		{
			MethodName: "ListDirectory",
			Handler:    _AgentService_ListDirectory_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _AgentService_DeleteFile_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _AgentService_ListServices_Handler,
		},
		{
			MethodName: "ServiceAction",
			Handler:    _AgentService_ServiceAction_Handler,
		},
		{
			MethodName: "ListProcesses",
			Handler:    _AgentService_ListProcesses_Handler,
		},
		{
			MethodName: "KillProcess",
			Handler:    _AgentService_KillProcess_Handler,
		},
		{
			MethodName: "SearchDockerHub",
			Handler:    _AgentService_SearchDockerHub_Handler,
		},
		{
			MethodName: "ProxyHttpRequest",
			Handler:    _AgentService_ProxyHttpRequest_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetMetrics",
			Handler:       _AgentService_GetMetrics_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ExecuteShell",
			Handler:       _AgentService_ExecuteShell_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "UploadFile",
			Handler:       _AgentService_UploadFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadFile",
			Handler:       _AgentService_DownloadFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "TailLog",
			Handler:       _AgentService_TailLog_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/agent.proto",
}
